### ISSUE TITLE
Parse failure in SvelteKit SSR

### ISSUE THREAD

**Issue by newtonyan** [portabletext/svelte-portabletext#17]
I got the following errors when I am simply trying to import PortableText. Works fine if SSR is disabled.

+page.svelte
```
<script lang="ts">
	import { PortableText } from '@portabletext/svelte';
</script>
```

got this error
```
Internal server error: Parse failure: Unexpected token (47:4)
Contents of line 47:                            {}: {
      at ssrTransformScript (/node_modules/vite/dist/node/chunks/dep-3007b26d.js:51814:15)
      at ssrTransform (/node_modules/vite/dist/node/chunks/dep-3007b26d.js:51789:12)
      at Object.ssrTransform (/node_modules/vite/dist/node/chunks/dep-3007b26d.js:61158:20)
      at loadAndTransform (/node_modules/vite/dist/node/chunks/dep-3007b26d.js:39489:24)
```

Here is my package.json, I have tried version "^1.0.1" and "2.0.0-0" for "@portabletext/svelte" and still got the same error.
```
"devDependencies": {
		"@portabletext/svelte": "2.0.0-0",
		"@rgossiaux/svelte-headlessui": "^1.0.2",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/adapter-static": "^1.0.0-next.47",
		"@sveltejs/kit": "^1.3.10",
		"@types/lodash": "^4.14.188",
		"@typescript-eslint/eslint-plugin": "^5.27.0",
		"@typescript-eslint/parser": "^5.27.0",
		"autoprefixer": "^10.4.13",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.18",
		"prettier": "^2.8.3",
		"prettier-plugin-svelte": "^2.7.0",
		"prettier-plugin-tailwindcss": "^0.2.2",
		"svelte": "^3.55.1",
		"svelte-check": "^2.7.1",
		"svelte-preprocess": "^4.10.7",
		"tailwindcss": "^3.2.1",
		"tslib": "^2.3.1",
		"typescript": "^4.7.4",
		"vite": "^4.1.1"
	},
	"type": "module",
	"dependencies": {
		"@sanity/client": "^3.4.1",
		"@sanity/image-url": "^1.0.2",
		"clsx": "^1.2.1",
		"dayjs": "^1.11.6",
		"iconify-icon": "^1.0.3",
		"lodash": "^4.17.21",
		"typesafe-i18n": "^5.21.0"
	}
```

**Comment by entrenadorhispano** [comment]
Same error... here... any solution?
