### ISSUE TITLE
Could not resolve dependency: npm ERR! peer svelte@"^3.47.0" from @portabletext/svelte@2.0.0

### ISSUE THREAD

**Issue by kamerat** [portabletext/svelte-portabletext#49]
When trying to upgrade to svelte 4, I get this error:
```
npm ERR! While resolving: myProject@1.2.3
npm ERR! Found: svelte@4.2.0
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^4.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^3.47.0" from @portabletext/svelte@2.0.0
npm ERR! node_modules/@portabletext/svelte
npm ERR!   dev @portabletext/svelte@"^2.0.0" from the root project
```

**Comment by stipsan** [comment]
Give [v2.1.1](https://github.com/portabletext/svelte-portabletext/releases) a shot ;)

**Comment by kamerat** [comment]
Thank you for following up on this, @stipsan! It sadly does not seem to resolve the error though.

**Comment by stipsan** [comment]
What's the error message how? It should at least change the peer range message if the dependency is installed correctly 😊

**Comment by kamerat** [comment]
My bad, it seems there's another error; ` The package may have incorrect main/module/exports specified in its package.json.`

```
[plugin:vite:import-analysis] Failed to resolve entry for package "@portabletext/svelte". The package may have incorrect main/module/exports specified in its package.json.
C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/src/lib/components/RichText/BlockContent.svelte
Error: Failed to resolve entry for package "@portabletext/svelte". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
    at resolvePackageEntry (file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vite/dist/node/chunks/dep-df561101.js:28688:5)
    at tryNodeResolve (file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Context.resolveId (file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.resolveId (file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
    at async TransformContext.resolve (file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vite/dist/node/chunks/dep-df561101.js:43923:23)
    at async normalizeUrl (file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vite/dist/node/chunks/dep-df561101.js:41793:34)
    at async file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vite/dist/node/chunks/dep-df561101.js:41945:47
    at async Promise.all (index 1)
    at async TransformContext.transform (file:///C:/Users/admin/Documents/xxxxxx/yyyyy/src/xxxxxx-web/node_modules/vi
    ```
